spring:
  application:
    name: banking-app
  datasource:
    #DB details
    url: jdbc:mysql://localhost:3306/bank
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true